### ISSUE TITLE
能收到推送消息吗？

### ISSUE THREAD

**Issue by zjz19901029** [hkizuna/cordova-plugin-umeng-push#2]
装了插件后，启动APP，在友盟后台发送消息，APP收不到，会是什么原因呢

**Comment by hkizuna** [comment]
@zjz19901029 可能是在开发环境下吗？开发环境下的话需要将设备token手动添加进去。

**Comment by zjz19901029** [comment]
我是打的release包，签了名的

**Comment by hkizuna** [comment]
你在后台推送的时候指定的是生产环境还是开发环境？有没有可能是推送证书没有配置好？
